controller_manager:
  ros__parameters:
    update_rate: 20
    use_sim_time: true

    omni_wheel_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


omni_wheel_controller:
  ros__parameters:
    wheel_offset: 1.047198 # pi/3 (60°) - matches wheel_3 position
    wheel_names:
      [
        "wheel_3_joint",  # at +60°
        "wheel_1_joint",  # at +180° (60° + 120°)  
        "wheel_2_joint",  # at -60° (60° + 240° = 300° = -60°)
      ]

    robot_radius: 0.105
    wheel_radius: 0.048

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true